---
title: "Censoring_example"
author: "Anton Holm"
date: '2020-04-28'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(19931031)
library(gridExtra)

Slope <- log(1.3)
Error_term <- rlnorm(1000, 0, 0.1)
Covariate <- rnorm(1000, 0, 1)
Response <- exp(Covariate*Slope)*Error_term
LOD <- sort(Error_term)[400]
Censored_data <- ifelse(Response<LOD, -LOD, Response) 
data <- as.data.frame(Censored_data) %>% 
  mutate(cens = Censored_data < 0) %>% 
  mutate(Covariates = Covariate) %>% 
  mutate(Censored_data = ifelse(Censored_data < 0, log(abs(Censored_data)/sqrt(2)), log(abs(Censored_data)))) %>% 
  mutate(cens = ifelse(cens == FALSE, "Uncensored", "Censored")) %>% 
  mutate(true_value = log(Response))

censored_plot <- data %>% ggplot(aes(x=Covariates, y = Censored_data, shape = cens)) + 
  geom_point(alpha = 0.3) +
  scale_y_continuous(limits = c(-0.9, 1)) +
  geom_hline(yintercept = log(LOD), linetype = 'dashed') +
  scale_shape_manual(values = c(16,1)) +
  xlim(-4, 4) +
  theme_minimal() +
  theme(plot.caption=element_text(hjust = 0), legend.position = c(0.77, 0.15), legend.background = element_rect(color = "black", 
    fill = NA, size =0.5, linetype = "solid"),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5),legend.title = element_blank()) +
  labs(x='X', y = 'Log(Y)', caption= "Figure 1a: Example of 1000 log-normal distributed
observations censored at LOQ") + 
  geom_text(aes(x = 3.5, y = 0), label = "LOQ", size = 3, show.legend = FALSE, family = "serif") +
  labs(x = 'X', y = 'Y')


uncensored_plot <- data %>% ggplot(aes(x=Covariates, y = true_value, shape = cens)) + 
  geom_point(alpha = 0.3) +
  scale_y_continuous(limits = c(-0.9, 1)) +
  geom_hline(yintercept = log(LOD), linetype = 'dashed') +
  scale_shape_manual(values = c(16,1)) +
  xlim(-4, 5) +
  theme_minimal() +
  theme(plot.caption=element_text(hjust = 0), legend.position = c(0.77, 0.15), legend.background = element_rect(color = "black", 
    fill = NA, size =0.5, linetype = "solid"),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5),legend.title = element_blank()) +
  labs(x='X', y = 'Log(Y)', caption= "Figure 1b: Example of the same 1000 log-normal
distributed observations without censoring") + 
  geom_text(aes(x = 4.5, y = 0), label = "LOQ", size = 3, show.legend = FALSE, family = "serif") +
  labs(x = 'X', y = 'Y')

grid.arrange(censored_plot, uncensored_plot, ncol = 2)

ggsave(plot = grid.arrange(censored_plot, uncensored_plot, ncol = 2), file = "Example_Censored_Plot.pdf")

```
