---
title: "Negative_Simulations_Testing"
author: "Anton Holm"
date: '2020-04-25'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(kableExtra)
```

```{r}
load("Simulations/slope1.01_res0.05_randomLOW_NEG.Rda")
load("Simulations/slope1.01_res0.05_randomHIGH_NEG.Rda")
load("Simulations/slope1.01_res0.5_randomLOW_NEG.Rda")
load("Simulations/slope1.01_res0.5_randomHIGH_NEG.Rda")
load("Simulations/slope1.01_res1.4_randomLOW_NEG.Rda")
load("Simulations/slope1.01_res1.4_randomHIGH_NEG.Rda")
load("Simulations/slope1.05_res0.05_randomLOW_NEG.Rda")
load("Simulations/slope1.05_res0.05_randomHIGH_NEG.Rda")
load("Simulations/slope1.05_res0.5_randomLOW_NEG.Rda")
load("Simulations/slope1.05_res0.5_randomHIGH_NEG.Rda")
load("Simulations/slope1.05_res1.4_randomLOW_NEG.Rda")
load("Simulations/slope1.05_res1.4randomHIGH_NEG.Rda")




Completed_df_neg <- full_join(df_1.01_0.05_Low_neg,df_1.01_0.05_HIGH_neg) %>%
  full_join(df_1.01_0.5_Low_neg) %>% 
  full_join(df_1.01_0.5_HIGH_neg) %>% 
  full_join(df_1.01_1.4_Low_neg) %>% 
  full_join(df_1.01_1.4_HIGH_neg) %>% 
  full_join(df_1.05_0.05_LOW_neg) %>% 
  full_join(df_1.05_0.05_HIGH_neg) %>% 
  full_join(df_1.05_0.5_LOW_neg) %>% 
  full_join(df_1.05_0.5_HIGH_neg) %>% 
  full_join(df_1.05_1.4_LOW_neg) %>% 
  full_join(df_1.05_1.4_HIGH_neg) %>% 
  mutate(CI_Lower = Beta - `Beta sd`*1.96) %>% 
  mutate(CI_Upper = Beta + `Beta sd`*1.96) %>% 
  mutate(Coverage = ifelse(Slope>CI_Lower & Slope < CI_Upper, 1, 0 ))

save(Completed_df_neg, file = "Rdata_Files/Completed_df_neg.Rda")
```


```{r}
######

with_bias_neg <- Completed_df_neg %>% 
  filter(Method != "True") %>% 
  mutate(diff = (Beta-Slope)^2) %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise(bias = mean(diff)) %>% 
  ungroup

with_standard_error_neg <- Completed_df_neg %>% 
  filter(Method != "True") %>% 
  mutate(diff = (Beta-Slope)^2) %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise("Standard Error" = sd(diff)/10) %>% 
  ungroup

with_coverage_neg <- Completed_df_neg %>% 
  filter(Method != "True") %>% 
  mutate(diff = (Beta-Slope)^2) %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise(coverage = mean(Coverage))

bias_coverage_neg <- with_bias_neg %>% 
  mutate(Coverage = with_coverage_neg$coverage)

save(bias_coverage_neg, file = "bias_coverage_df_neg.Rda")
```


```{r}
####

Variances_neg <- Completed_df_neg %>% 
  filter(Method != "True") %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise(Variance = sd(Beta)^2)


All_Summary_Stats_neg <- bias_coverage_neg %>% 
  inner_join(Variances_neg, by = c('Limit fraction', 'Slope', 'Std', 'Random Effects', 'Method')) %>% 
  mutate(MSE = bias + Variance) %>% 
  mutate("Standard Error" = with_standard_error_neg$`Standard Error`)

save(All_Summary_Stats_neg, file = "Rdata_Files/All_Summary_Stats_neg.Rda")

load("Rdata_Files/All_Summary_Stats_neg.Rda")
```


```{r}

#####

#LOQ 30, Slope -1% Table
Full_Summary_Stats_neg <- All_Summary_Stats_neg


Summary_LOQ30_Slope1.01_neg <- Full_Summary_Stats_neg %>% 
  filter(`Limit fraction` == 0.3) %>% 
  filter(Slope > -0.05) %>% 
  mutate(Slope = '-1%') %>%
  mutate(bias = round(bias, digits = 4)) %>% 
  mutate(Variance = round(Variance, digits = 4)) %>% 
  mutate(MSE = round(MSE, digits = 4)) %>% 
  select(-c(`Limit fraction`, Slope)) %>% 
  arrange(Std) %>% 
    mutate("Standard Error" = round(sqrt(Variance/(100))*2*abs(bias), digits = 4))%>% 
  mutate(Method = ifelse(Method == "Tobit", "LMMC", "Substitution"))

colnames(Summary_LOQ30_Slope1.01_neg) <- c("Individual Sd", "Random Effect", "Method", "$(\\hat{\\beta} - \\beta)^2$", "Coverage", "Var($\\hat{\\beta}$)", "MSE", "Se($(\\hat{\\beta}-\\beta)^2$)")

Table_LOQ30_Slope1.01_neg <- kable(Summary_LOQ30_Slope1.01_neg, escape = FALSE, format = "latex", booktabs = T, align = "l", caption = "Summary statistics of simulations at 30\\% censored data and a 1\\% yearly decrease") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle") %>% 
  kable_styling(latex_options="scale_down")

save(Table_LOQ30_Slope1.01_neg, file = "Table_LOQ30_Slope1.01_neg.Rda")

Table_LOQ30_Slope1.01_neg

#----------------------------------------------------------------------

#LOQ 30, Slope 5% Table
Summary_LOQ30_Slope1.05_neg <- Full_Summary_Stats_neg %>% 
  filter(`Limit fraction` == 0.3) %>% 
  filter(Slope < -0.05) %>% 
  mutate(Slope = '-5%') %>%
  mutate(bias = round(bias, digits = 4)) %>% 
  mutate(Variance = round(Variance, digits = 4)) %>% 
  mutate(MSE = round(MSE, digits = 4)) %>% 
  select(-c(`Limit fraction`, Slope)) %>% 
  arrange(Std) %>% 
    mutate("Standard Error" = round(sqrt(Variance/(100))*2*abs(bias), digits = 4))%>% 
  mutate(Method = ifelse(Method == "Tobit", "LMMC", "Substitution"))

colnames(Summary_LOQ30_Slope1.05_neg) <- c("Individual Sd", "Random Effect", "Method", "$(\\hat{\\beta} - \\beta)^2$", "Coverage", "Var($\\hat{\\beta}$)", "MSE", "Se($(\\hat{\\beta}-\\beta)^2$)")

Table_LOQ30_Slope1.05_neg <- kable(Summary_LOQ30_Slope1.05_neg, escape = FALSE, format = "latex", booktabs = T, align = "l", caption = "Summary statistics of simulations at 30\\% censored data and a 5\\% yearly decrease") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle") %>% 
  kable_styling(latex_options="scale_down")
              

save(Table_LOQ30_Slope1.05_neg, file = "Table_LOQ30_Slope1.05_neg.Rda")

Table_LOQ30_Slope1.05_neg


#----------------------------------------------------------------------

#LOQ 60, Slope 1% Table
Summary_LOQ60_Slope1.01_neg <- Full_Summary_Stats_neg %>% 
  filter(`Limit fraction` == 0.6) %>% 
  filter(Slope > -0.05) %>% 
  mutate(Slope = '-1%') %>%
  mutate(bias = round(bias, digits = 4)) %>% 
  mutate(Variance = round(Variance, digits = 4)) %>% 
  mutate(MSE = round(MSE, digits = 4)) %>% 
  select(-c(`Limit fraction`, Slope)) %>% 
  arrange(Std) %>% 
    mutate("Standard Error" = round(sqrt(Variance/(100))*2*abs(bias), digits = 4))%>% 
  mutate(Method = ifelse(Method == "Tobit", "LMMC", "Substitution"))

colnames(Summary_LOQ60_Slope1.01_neg) <- c("Individual Sd", "Random Effect", "Method", "$(\\hat{\\beta} - \\beta)^2$", "Coverage", "Var($\\hat{\\beta}$)", "MSE", "Se($(\\hat{\\beta}-\\beta)^2$)")

Table_LOQ60_Slope1.01_neg <- kable(Summary_LOQ60_Slope1.01_neg, escape = FALSE, format = "latex", booktabs = T, align = "l", caption = "Summary statistics of simulations at 60\\% censored data and a 1\\% yearly decrease") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle") %>% 
  kable_styling(latex_options="scale_down")
              

save(Table_LOQ60_Slope1.01_neg, file = "Table_LOQ60_Slope1.01_neg.Rda")

Table_LOQ60_Slope1.01_neg


#----------------------------------------------------------------------

#LOQ 60, Slope 5% Table
Summary_LOQ60_Slope1.05_neg <- Full_Summary_Stats_neg %>% 
  filter(`Limit fraction` == 0.6) %>% 
  filter(Slope < -0.05) %>% 
  mutate(Slope = '-5%') %>%
  mutate(bias = round(bias, digits = 4)) %>% 
  mutate(Variance = round(Variance, digits = 4)) %>% 
  mutate(MSE = round(MSE, digits = 4)) %>% 
  select(-c(`Limit fraction`, Slope)) %>% 
  arrange(Std) %>% 
    mutate("Standard Error" = round(sqrt(Variance/(100))*2*abs(bias), digits = 4))%>% 
  mutate(Method = ifelse(Method == "Tobit", "LMMC", "Substitution"))

colnames(Summary_LOQ60_Slope1.05_neg) <- c("Individual Sd", "Random Effect", "Method", "$(\\hat{\\beta} - \\beta)^2$", "Coverage", "Var($\\hat{\\beta}$)", "MSE", "Se($\\hat{\\beta}$)")

Table_LOQ60_Slope1.05_neg <- kable(Summary_LOQ60_Slope1.05_neg, escape = FALSE, format = "latex", booktabs = T, align = "l", caption = "Summary statistics of simulations at 60\\% censored data and a 5\\% yearly decrease") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle") %>% 
  kable_styling(latex_options="scale_down")
              

save(Table_LOQ60_Slope1.05_neg, file = "Table_LOQ60_Slope1.05_neg.Rda")

Table_LOQ60_Slope1.05_neg
```


```{r}
####

betas_neg <- Completed_df_neg %>% 
  filter(Method != "True") %>% 
   mutate(Slope_Perc = ifelse(Slope > -0.05, "1% yearly decrease", "5% yearly decrease")) %>% 
  mutate(`Limit fraction` = ifelse(`Limit fraction` == 0.3, "30% censoring", "60% Censoring"))

####

tobit_betas_individual_high_neg <- betas_neg %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method)) %>% 
  filter(Std == 1.4)


museum_betas_individual_high_neg <- betas_neg %>% 
  filter(Method == "Museum") %>% 
  select(-(Method)) %>% 
  filter(Std == 1.4)

betas_spread_individual_high_neg <- tobit_betas_individual_high_neg %>% 
  mutate(Museum_Beta = museum_betas_individual_high_neg$Beta)


Plot_High_Individual_Variance_neg <- betas_spread_individual_high_neg %>% ggplot(aes(x=Beta, y=Museum_Beta, col = `Random Effects`, shape = `Random Effects`)) +
  facet_grid(Slope_Perc ~ `Limit fraction`) +
  geom_point(alpha = 0.5) + 
  theme_minimal() +
  theme(plot.caption=element_text(hjust = 0), legend.background = element_rect(color = "black", 
    fill = NA, size =0.5, linetype = "solid"),
    panel.border = element_rect(colour = "black", fill=NA, size=0.5),legend.title = element_text(color = "black", size = 8), legend.position = "top")+ 
   geom_hline(data = data.frame(Slope_Perc="1% yearly decrease", y=log(0.99)), mapping=aes(yintercept=y)) +
   geom_vline(data = data.frame(Slope_Perc="1% yearly decrease", x=log(0.99)), mapping=aes(xintercept=x)) +
  geom_hline(data = data.frame(Slope_Perc="5% yearly decrease", y=log(0.95)), mapping=aes(yintercept=y))+
   geom_vline(data = data.frame(Slope_Perc="5% yearly decrease", x=log(0.95)), mapping=aes(xintercept=x)) +
  labs(caption = "Figure 14: Plotting the estimated slopes for the substitution method and the LMMC model against eachother having the variance of individual specimens 
set to high. The vertical and horizontal lines correspond to the true value of the slope.",
  x = 'Estimates of the LMMC Model', y = 'Estimates from Substitution')

save(Plot_High_Individual_Variance_neg, file = "Rdata_Files/Plot_High_Individual_Variance_neg.Rda")
Plot_High_Individual_Variance_neg




tobit_betas_individual_low_neg <- betas_neg %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.05)


museum_betas_individual_low_neg <- betas_neg %>% 
  filter(Method == "Museum") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.05)

betas_spread_individual_low_neg <- tobit_betas_individual_low_neg %>% 
  mutate(Museum_Beta = museum_betas_individual_low_neg$Beta)


Plot_Low_Individual_Variance_neg <- betas_spread_individual_low_neg %>% ggplot(aes(x=Beta, y=Museum_Beta, col = `Random Effects`, shape = `Random Effects`)) +
  facet_grid(Slope_Perc ~ `Limit fraction`) +
  geom_point(alpha = 0.5) + 
  theme_minimal() +
  theme(plot.caption=element_text(hjust = 0.8), legend.background = element_rect(color = "black", 
    fill = NA, size =0.5, linetype = "solid"),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5),legend.title = element_text(color = "black", size = 8), legend.position = "top")+ 
   geom_hline(data = data.frame(Slope_Perc="1% yearly decrease", y=log(0.99)), mapping=aes(yintercept=y)) +
   geom_vline(data = data.frame(Slope_Perc="1% yearly decrease", x=log(0.99)), mapping=aes(xintercept=x)) +
  geom_hline(data = data.frame(Slope_Perc="5% yearly decrease", y=log(0.95)), mapping=aes(yintercept=y))+
   geom_vline(data = data.frame(Slope_Perc="5% yearly decrease", x=log(0.95)), mapping=aes(xintercept=x)) +
  labs(caption = "Figure 12: Plotting the estimated slopes for the substitution method and the LMMC modelagainst eachother having the variance of individual specimens
set to low. The vertical and horizontal lines correspond to the true value of the slope.",
  x = 'Estimates of the LMMC Model', y = 'Estimates from Substitution')

save(Plot_Low_Individual_Variance_neg, file = "Rdata_Files/Plot_Low_Individual_Variance_neg.Rda")

Plot_Low_Individual_Variance_neg


tobit_betas_individual_medium_neg <- betas_neg %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.5)


museum_betas_individual_medium_neg <- betas_neg %>% 
  filter(Method == "Museum") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.5)

betas_spread_individual_medium_neg <- tobit_betas_individual_medium_neg %>% 
  mutate(Museum_Beta = museum_betas_individual_medium_neg$Beta)


Plot_Medium_Individual_Variance_neg <- betas_spread_individual_medium_neg %>% ggplot(aes(x=Beta, y=Museum_Beta, col = `Random Effects`, shape = `Random Effects`)) +
  facet_grid(Slope_Perc ~ `Limit fraction`) +
  geom_point(alpha = 0.5) + 
  theme_minimal() +
  theme(plot.caption=element_text(hjust = 0.8), legend.background = element_rect(color = "black", 
    fill = NA, size =0.5, linetype = "solid"),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5),legend.title = element_text(color = "black", size = 8), legend.position = "top")+ 
   geom_hline(data = data.frame(Slope_Perc="1% yearly decrease", y=log(0.99)), mapping=aes(yintercept=y)) +
   geom_vline(data = data.frame(Slope_Perc="1% yearly decrease", x=log(0.99)), mapping=aes(xintercept=x)) +
  geom_hline(data = data.frame(Slope_Perc="5% yearly decrease", y=log(0.95)), mapping=aes(yintercept=y))+
   geom_vline(data = data.frame(Slope_Perc="5% yearly decrease", x=log(0.95)), mapping=aes(xintercept=x)) +
  labs(caption = "Figure 13: Plotting the estimated slopes for the substitution method and the LMMC model against eachother having the variance of individual specimens 
set to medium. The vertical and horizontal lines correspond to the true value of the slope.",
  x = 'Estimates of the LMMC Model', y = 'Estimates from Substitution')

save(Plot_Medium_Individual_Variance_neg, file = "Rdata_Files/Plot_Medium_Individual_Variance_neg.Rda")


  ggsave(plot = Plot_Medium_Individual_Variance_neg, file = "Beta_Medium_Variance_neg.pdf", scale = 1.5, width = 6)
  ggsave(plot = Plot_Low_Individual_Variance_neg, file = "Beta_Low_Variance_neg.pdf", scale = 1.5, width = 6)
  ggsave(plot = Plot_High_Individual_Variance_neg, file = "Beta_High_Variance_neg.pdf", scale = 1.5, width = 6)
```