---
title: "Testing Things"
author: "Anton Holm"
date: '2020-04-08'
output: pdf_document


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
```

```{r}
library(kableExtra)
library(knitr)
library(tidyverse)
library(tinytex)
library(directlabels)


df_slope0.01_res0.05 %>% 
  group_by(Method) %>% 
  summarise(mean(Beta))

df_slope0.01_res0.05 %>% 
  ggplot(aes(x=simulation, y=Beta, color=Method)) +
  geom_line()

df_slope0.01_res0.05 %>% 
  group_by(Method, `Limit fraction`) %>% 
  summarise(mean(Intercept))



dataset_censored %>% as.data.frame() %>% 
  filter(. < 0) %>%  count()

length(dataset_censored)


df_slope0.05_res0.05 %>% 
  group_by(Method, `Limit fraction`) %>% 
  summarise(mean(Intercept))


df_slope0.05_res0.05 %>% 
  ggplot(aes(x=simulation, y= Beta, color = Method)) + 
  geom_line()


df_slope0.01_res1.4 %>% 
  group_by(Method, `Limit fraction`) %>% 
  summarise(mean(Beta))

df_slope0.05_res1.4 %>% 
  ggplot(aes(x=simulation, y=Beta, col=Method)) + geom_line()

df_slope0.01_res1.4 %>% 
  mutate(diff = abs(Beta-Slope)) %>% 
  group_by(Method, `Limit fraction`) %>% 
  summarise(min(diff))

load("s05_res05.Rda")
df_slope0.05_res0.05

https://www.youtube.com/watch?v=AnbiNaVp3eQ
https://cran.r-project.org/web/packages/lmec/lmec.pdf
https://babel.hathitrust.org/cgi/pt?id=mdp.39015059153646&view=1up&seq=6
http://nrm.diva-portal.org/smash/get/diva2:1090746/FULLTEXT01.pdf
https://tools.kib.ki.se/referensguide/apa/rapporter-rapporterielektroniskformmednamngivenforfattare
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4377318/
  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5138145/
  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4377318/
  
  http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.56.3943&rep=rep1&type=pdf

fitted
summary(true_model)

df_slope0.05_res0.05 %>% 
  ggplot(aes(x=simulation, y=Beta, col=Method)) + geom_line()

load("s1.01_r1.4.Rda")
load("s1.01_r0.05.Rda")
load("s1.05_r0.05.Rda")
load("s1.05_r1.4.Rda")

slope0.01_res0.05
slope0.01_res1.4
slope0.05_res0.05
slope0.05_res1.4


finished_df <- full_join(slope0.01_res0.05, slope0.01_res1.4) %>% 
  full_join(slope0.05_res0.05) %>% 
  full_join(slope0.05_res1.4)

save(finished_df, file = "finished_df.Rda")

finished_df %>% 
  mutate(diff = abs(Beta - Slope)) %>% 
  group_by(Method) %>% 
  summarise(mean(diff))


metals <- read_csv("../metals.csv")

metals %>% 
  group_by(YEAR, LOC) %>% 
  summarise(std = sd(NI)) %>% 
  ungroup() %>% 
  na.omit() %>% 
  group_by(YEAR) %>% 
  summarise(max(std))
  
min_variances <- metals %>% 
  group_by(LOC, YEAR) %>% 
  summarise(std = sd(NI)) %>% 
  ungroup() %>% 
  na.omit() %>% 
  group_by(YEAR) %>% 
  summarise(min_std = min(std)) %>% 
  select('min_std')

max_variances <- metals %>% 
  group_by(LOC, YEAR) %>% 
  summarise(std = sd(NI)) %>% 
  ungroup() %>% 
  na.omit() %>% 
  group_by(YEAR) %>% 
  summarise(max_std = max(std)) %>% 
  select('max_std')

Yearly_variances <- c()

metals %>% filter(YEAR == 2015) %>% group_by(LOC) %>% count()

metals %>% group_by(LOC, YEAR) %>% summarise(sd(NI))

target_locations <- metals %>% group_by(LOC, YEAR) %>% count() %>% filter(n>9) %>% ungroup() %>% select(LOC) %>% filter(LOC != "Utlängan (spring)") %>% filter(LOC !="Ängskärsklubb (spring)") %>% filter(LOC != "Örefjärden")


locations_w_many_obs <- metals %>% filter(LOC %in% target_locations[[1]])

min_std_yearly <- locations_w_many_obs %>% group_by(LOC, YEAR) %>%  summarise(std = sd(NI)) %>% na.omit() %>% ungroup() %>% group_by(YEAR) %>% summarise(min_sd = min(std))

max_std_yearly <- locations_w_many_obs %>% group_by(LOC, YEAR) %>%  summarise(std = sd(NI)) %>% na.omit() %>% ungroup() %>% group_by(YEAR) %>% summarise(max_sd = max(std))
yearly_variances <- cbind(min_std_yearly[,2], max_std_yearly[,2])


save(yearly_variances, file="yearly_variances.Rda")



df_1.01_1.4_HIGH

df_1.05_1.4_HIGH
library(tidyverse)
NI_data <- metals %>% 
  select(NI) %>% 
  na.omit() %>% 
  filter(NI>0)
NI_data[[1]]




df_1.05_1.4_HIGH %>% ggplot(aes(x = abs(Beta), y = `Beta sd`, col = Method)) + geom_point()

df_1.05_1.4_HIGH %>% mutate(diff = abs(Beta - Slope)) %>% ggplot(aes(x=diff, y=Beta, col = Method)) + geom_point()

split_df <- df_1.05_1.4_HIGH %>% dplyr::select(simulation, Method, `Beta`) %>% spread(Method, `Beta`)

split_df %>% ggplot(aes(x=Museum, y=True)) + geom_point()

df_1.05_1.4_HIGH %>% 
  mutate(diff=abs(Beta-Slope)) %>% 
  group_by(Method) %>% 
  summarise(bias = mean(diff))

df_1.05_1.4_HIGH %>% 
  group_by(Method) %>% 
  mutate(mean_beta = mean(Beta)) %>% 
  mutate(bias = mean_beta - Slope)





#____________________________________________________

```


```{r}
load("Simulations/slope1.01_res0.05_randomHIGH.Rda")
load("Simulations/slope1.01_res0.05_randomLOW.Rda")
load("Simulations/slope1.01_res1.4_randomHIGH.Rda")
load("Simulations/slope1.01_res1.4_randomLOW.Rda")
load("Simulations/slope1.05_res0.05_randomHIGH.Rda")
load("Simulations/slope1.05_res0.05_randomLOW.Rda")
load("Simulations/slope1.05_res1.4_randomHIGH.Rda")
load("Simulations/slope1.05_res1.4_randomLOW.Rda")












Completed_df <- full_join(df_1.01_0.05_LOW,df_1.01_0.05_HIGH) %>%
  full_join(df_1.01_1.4_LOW) %>% 
  full_join(df_1.01_1.4_HIGH) %>% 
  full_join(df_1.05_0.05_LOW) %>% 
  full_join(df_1.05_0.05_HIGH) %>% 
  full_join(df_1.05_1.4_LOW) %>% 
  full_join(df_1.05_1.4_HIGH) %>% 
  mutate(CI_Lower = Beta - `Beta sd`*1.96) %>% 
  mutate(CI_Upper = Beta + `Beta sd`*1.96) %>% 
  mutate(Coverage = ifelse(Slope>CI_Lower & Slope < CI_Upper, 1, 0 ))

save(Completed_df, file = "Completed_df.Rda")

Completed_df %>% 
  mutate(diff = abs(Beta-Slope)) %>% 
  group_by(Method, Std, Slope, `Random Effects`, `Limit fraction`) %>% 
  summarise(Bias = mean(Coverage)) %>% 
  arrange(Bias)


Completed_df %>% filter(Method == "Museum")


Completed_df %>% 
  mutate(diff = abs(Beta-Slope)) %>%
  mutate(diff2 = Beta-Slope) %>% 
  group_by(Method) %>% 
  summarise(mean(diff2))

example_of_one_simulation <- cbind(kovariat, predictors, cens) %>% as.data.frame() %>% mutate(cens = as.factor(cens)) %>% mutate(cens = ifelse(cens = 0, "Uncensored", "Censored"))

save(example_of_one_simulation, file = "example_of_simulation.Rda")
example_graph <- example_of_one_simulation %>% 
  ggplot(aes(x=kovariat, y=log(predictors), shape = cens)) + 
  geom_point() +
  geom_hline(yintercept = log(1.723875), linetype = 'dashed') +
  scale_shape_manual(values = c(16,1)) +
  xlim(-5, 6) +
  theme_minimal() +
  theme(plot.caption=element_text(hjust = 0.2), legend.position = c(0.9, 0.2), legend.background = element_rect(color = "black", 
    fill = NA, size =0.5, linetype = "solid"),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5),legend.title = element_blank()) +
  labs(x='X', y = 'Log(Y)', caption= "Figure 2: Simulated data with 60% censoring, large variations and slope representing 5% yearly increase.") + 
  geom_text(aes(x = 6, y = 1.1), label = "LOQ", size = 3, show.legend = FALSE, family = "serif") +
  labs(x = 'Years', y = 'Log(Concentration)')
  

save(example_graph, file = "Rdata_Files/example_graph.Rda")


cor(kovariat, log(predictors))

metals

with_standard_error
```


```{r}
with_bias <- Completed_df %>% 
  filter(Method != "True") %>% 
  mutate(diff = (Beta-Slope)^2) %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise(bias = mean(diff)) %>% 
  ungroup

with_standard_error <- Completed_df %>% 
  filter(Method != "True") %>% 
  mutate(diff = (Beta-Slope)^2) %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise("Standard Error" = sd(diff)/10) %>% 
  ungroup

with_coverage <- Completed_df %>% 
  filter(Method != "True") %>% 
  mutate(diff = (Beta-Slope)^2) %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise(coverage = mean(Coverage))

bias_coverage <- with_bias %>% 
  mutate(Coverage = with_coverage$coverage)

save(bias_coverage, file = "bias_coverage_df.Rda")
save(Completed_df, file = "Completed_df.Rda")

load("Completed_df.Rda")
Completed_df




Variances <- Completed_df %>% 
  filter(Method != "True") %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise(Variance = sd(Beta)^2)


All_Summary_Stats <- bias_coverage %>% 
  inner_join(Variances, by = c('Limit fraction', 'Slope', 'Std', 'Random Effects', 'Method')) %>% 
  mutate(MSE = bias + Variance) %>% 
  mutate("Standard Error" = with_standard_error$`Standard Error`)

save(All_Summary_Stats, file = "Rdata_Files/All_Summary_Stats.Rda")


All_Summary_Stats


```

```{r}
table_data <- Completed_df %>% 
  group_by(Method, `Limit fraction`, Std, Slope, `Random Effects`) %>% 
  mutate(count=1:n()) %>% 
  ungroup %>% 
  mutate(Method = ifelse(count==1, as.character(Method), NA)) %>% 
  filter(Method=="True")

#It's 30% Censored, Slope 1%
Summary_LOQ30_Slope1.01 <- All_Summary_Stats %>% 
  filter(`Limit fraction` == 0.3) %>% 
  filter(Slope < 0.01) %>% 
  mutate(Slope = '1%') %>%
  select(-c(`Limit fraction`, Slope)) %>% 
  group_by(Std) %>% 
  mutate(count = 1:n()) %>% 
  ungroup %>% 
  mutate(Std = ifelse(count == 1, Std, NA)) %>% 
  group_by(`Random Effects`) %>% 
  mutate(count = 1:n()) %>% 
  ungroup %>% 
  mutate(`Random Effects` = ifelse(count == 1| count == 3, `Random Effects`, NA)) %>% 
  select(-c(count, MSE )) %>% 
  mutate(bias = round(bias, digits = 4)) %>% 
  rename(Bias = bias) %>% 
  mutate(Variance = round(Variance, digits = 4))



LOQ30_Slope1.01_table <- htmlTable(Summary_LOQ30_Slope1.01, rnames=FALSE, align="llllll", align.header="cccccc",
          col.rgroup = rep(c("none", "gray93"), each=2),
          css.cell = c("padding-left: 0em","padding-left: 1em",rep("padding-left: 2em",5)))

save(LOQ30_Slope1.01_table, file = "LOQ30_Slope1.01_table.Rda")

htmlTable(Summary_LOQ30_Slope1.01, rnames=FALSE, align="llllll", align.header="cccccc",
          col.rgroup = rep(c("none", "gray93"), each=2),
          css.cell = c("padding-left: 0em","padding-left: 1em",rep("padding-left: 2em",5)))


LOQ30_Slope1.01_table <- htmlTable(Summary_LOQ30_Slope1.01, rnames=FALSE, align="llllll", align.header="cccccc",
          col.rgroup = rep(c("none", "gray93"), each=2),
          css.cell = c("padding-left: 0em","padding-left: 1em",rep("padding-left: 2em",5)),
          caption = "Table 1: Summary statistics having 30% censored observations and a yearly increase of 1% on the original scale.")

png("LOQ30_Slope1.01_table_img.png")
p<-tableGrob(LOQ30_Slope1.01_table)
grid.arrange(p)
dev.off()




Summary_LOQ30_Slope1.01


knitr::kable(Summary_LOQ30_Slope1.01, caption = "Group Rows", booktabs = T) %>%
kable_styling() %>%
pack_rows("Group 1", 4, 7, latex_gap_space = "2em") %>%
pack_rows("Group 2", 8, 10)







All_Summary_Stats


collapse_rows_dt <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
C2 = c(rep("c", 7), rep("d", 3), rep("c", 2), rep("d", 3)),
C3 = 1:15,
C4 = sample(c(0,1), 15, replace = TRUE))

ex_table <- kable(collapse_rows_dt, format = "latex", booktabs = T, align = "l") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle")

save(ex_table, file = "ex_table.Rda")


kable(iris, format = "latex")
```

```{r}
knitr::kable(iris, format = "html")


kable(collapse_rows_dt, format = "html", booktabs = T, align = "l") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle")




Summary_LOQ30_Slope1.01 <- All_Summary_Stats %>% 
  filter(`Limit fraction` == 0.3) %>% 
  filter(Slope < 0.01) %>% 
  mutate(Slope = '1%') %>%
  select(-c(`Limit fraction`, Slope))

test_table <- kable(Summary_LOQ30_Slope1.01, format = "latex", booktabs = T, align = "l") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle")

save(test_table, file = "test_table.Rda")





betas_LOQ0.3_Slope1.05_LL <- Completed_df %>%
  filter(`Limit fraction` == 0.3) %>% 
  filter(Slope > 0.01) %>% 
  filter(Std == 0.05) %>% 
  filter(Method != 'True') %>% 
  filter(`Random Effects` == "Low") %>% 
  select(simulation, Method, Beta) %>% 
  spread(Method, Beta)

betas_LOQ0.6_Slope1.05_LL <- Completed_df %>%
  filter(`Limit fraction` == 0.6) %>% 
  filter(Slope > 0.01) %>% 
  filter(Std == 0.05) %>% 
  filter(Method != 'True') %>% 
  filter(`Random Effects` == "Low") %>% 
  select(simulation, Method, Beta) %>% 
  spread(Method, Beta)

betas_LOQ0.3_Slope1.01_LL <- Completed_df %>%
  filter(`Limit fraction` == 0.3) %>% 
  filter(Slope < 0.01) %>% 
  filter(Std == 0.05) %>% 
  filter(Method != 'True') %>% 
  filter(`Random Effects` == "Low") %>% 
  select(simulation, Method, Beta) %>% 
  spread(Method, Beta)

betas_LOQ0.6_Slope1.01_LL <- Completed_df %>%
  filter(`Limit fraction` == 0.6) %>% 
  filter(Slope < 0.01) %>% 
  filter(Std == 0.05) %>% 
  filter(Method != 'True') %>% 
  filter(`Random Effects` == "Low") %>% 
  select(simulation, Method, Beta) %>% 
  spread(Method, Beta)

plot_betas %>% 
  ggplot(aes(x=Museum, y=Tobit)) +
  geom_point()

save(Completed_df, file = "Completed_df.Rda")
Completed_df_fixed <- Completed_df %>% mutate(`Random Effects` = replace(`Random Effects`, `Random Effects` == "HIGH", "High"))
betas <- Completed_df %>% filter(Method != "True")


tobit_betas_low <- betas %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.05) %>% 
  filter(`Random Effects` == "Low")


museum_betas_low <- betas %>% 
  filter(Method == "Museum") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.05) %>% 
  filter(`Random Effects` == "Low")

betas_spread_low <- inner_join(tobit_betas_low, museum_betas_low, by = c("simulation", "Limit fraction", "Slope", "Std", "Random Effects"))


betas_spread_low %>% ggplot(aes(x=Beta.x, y=Beta.y)) + geom_point() + facet_grid(`Limit fraction` ~ Slope)



tobit_betas_high <- betas %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method)) %>% 
  filter(Std == 1.4) %>% 
  filter(`Random Effects` == "High") %>% 
  mutate(Beta = Beta/Slope)


museum_betas_high <- betas %>% 
  filter(Method == "Museum") %>% 
  select(-(Method)) %>% 
  filter(Std == 1.4) %>% 
  filter(`Random Effects` == "High") %>% 
  mutate(Beta = Beta/Slope)

betas_spread_high <- inner_join(tobit_betas_high, museum_betas_high, by = c("simulation", "Limit fraction", "Slope", "Std", "Random Effects"))


betas_spread_high %>% ggplot(aes(x=Beta.x, y=Beta.y)) + geom_point() + facet_grid(`Limit fraction` ~ Slope)

Completed_df %>% 
  filter(`Random Effects` == "HIGH")



Completed_df %>% 
  group_by(`Limit fraction`, Slope, Std, Method, `Random Effects`) %>% 
  mutate(diff = abs(Beta-Slope)) %>% 
  summarise(diff = max(diff)) %>% 
  filter(Method != "True") %>% 
  arrange(desc(diff))




low_slope_df <- Completed_df %>% 
  filter(Method != "True") %>% 
  filter(Slope < 0.01) %>% 
  mutate(simulation = ifelse(`Limit fraction` == 0.6, simulation-100, simulation))


tobit_betas <- betas %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method))

museum_betas <- betas %>% 
  filter(Method == "Museum") %>% 
  select(-(Method)) 

spread_betas <- tobit_betas %>% 
  mutate(museum_beta = museum_betas$Beta)


spread_betas  %>% 
  ggplot(aes(x=Beta, y=museum_beta)) +
  facet_grid(Slope_Perc ~ `Limit fraction`) +
  geom_point() + 
   geom_hline(data = data.frame(Slope_Perc="1%", y=log(1.01)), mapping=aes(yintercept=y)) +
   geom_vline(data = data.frame(Slope_Perc="1%", x=log(1.01)), mapping=aes(xintercept=x)) +
  geom_hline(data = data.frame(Slope_Perc="5%", y=log(1.05)), mapping=aes(yintercept=y))+
   geom_vline(data = data.frame(Slope_Perc="5%", x=log(1.05)), mapping=aes(xintercept=x)) +
  labs(caption = "Figure 2: Plotting the estimated slopes for the Museum model and Tobit model against eachother
having the variance of both error terms set to high.")




betas_spread_individual_low %>% 
  group_by(Slope, Std, `Limit fraction`, `Random Effects`) %>% 
  summarise(correlation = cor(Beta,Museum_Beta))


tobit_betas_low <- betas %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method))


museum_betas_low <- betas %>% 
  filter(Method == "Museum") %>% 
  select(-(Method))

betas_spread <- tobit_betas_low %>% 
  mutate(Museum_Beta = museum_betas_low$Beta)


Three_metals <- metals %>% 
  select(YEAR, SPECIES, LOC, NI, CR, PB)

Fladen_Herring <- Three_metals %>% filter(LOC == "Fladen") %>% mutate(PB = ifelse(PB < 0, log(abs(PB/sqrt(2))), log(abs(PB)))) %>% filter(SPECIES == "Herring")
lm(PB~YEAR, data=Fladen_Herring)


Fladen_Metals <- Three_metals %>% 
  filter(LOC == "Fladen") %>% 
  filter(SPECIES == "Herring")




Vector_values <- Fladen_Metals
N = length(Vector_values$PB)

Y_varden <- log(abs(Vector_values$PB))
censor_indikator <- Vector_values$PB < 0
X <- cbind(rep_len(1,N), Vector_values$YEAR)
Z <- matrix(rep_len(1,N), ncol=1)
cluster <- as.numeric(factor(Vector_values$YEAR))
fitted <- lmec(Y_varden, censor_indikator, X, Z, cluster, maxstep = 20, method = "ML")

fitted



library(NADA)


PB_Fladen <- List_each_LOC[[1]] %>% filter(SPECIES == "Herring") %>% select(PB) %>% mutate(cens = PB < 0)

PB_ros_Fladen <- cenros(log(abs(PB_Fladen[['PB']])), PB_Fladen[['cens']], forwardT= NULL , reverseT = NULL)

PB_Fladen_Plot <- plot(PB_ros_Fladen)


PB_Harufjarden <- List_each_LOC[[2]] %>% filter(SPECIES == "Herring") %>% select(PB) %>% mutate(cens = PB < 0)

PB_ros_Harufjarden <- cenros(log(abs(PB_Harufjarden[['PB']])), PB_Harufjarden[['cens']], forwardT= NULL, reverseT = NULL)

PB_Harufjarden_Plot <- plot(PB_ros_Harufjarden)


PB_Landsort <- List_each_LOC[[3]] %>% filter(SPECIES == "Herring") %>% select(PB) %>% mutate(cens = PB < 0) %>% arrange(PB)
PB_Landsort[5:7,2] = TRUE

```

```{r}
PB_ros_Landsort <- cenros(log(abs(PB_Landsort[['PB']])), PB_Landsort[['cens']], forwardT= NULL, reverseT = NULL)

plot(PB_ros_Landsort)

PB_Utlangan <- List_each_LOC[[4]] %>% filter(SPECIES == "Herring") %>% select(PB) %>% mutate(cens = PB < 0)

PB_ros_Utlangan <- cenros(log(abs(PB_Utlangan[['PB']])), PB_Utlangan[['cens']], forwardT= NULL, reverseT = NULL)
metals



PB_Vaderoarna<- List_each_LOC[[5]] %>% filter(SPECIES == "Herring") %>% select(PB) %>% mutate(cens = PB < 0)

PB_ros_Vaderoarna <- cenros(log(abs(PB_Vaderoarna[['PB']])), PB_Vaderoarna[['cens']], forwardT= NULL, reverseT = NULL)

PB_Vaderoarna_Plot <- plot(PB_ros_Vaderoarna)


PB_Angkarsklubb<- List_each_LOC[[6]] %>% filter(SPECIES == "Herring") %>% select(PB) %>% mutate(cens = PB < 0)

PB_ros_Angkarsklubb <- cenros(log(abs(PB_Angkarsklubb[['PB']])), PB_Angkarsklubb[['cens']], forwardT = NULL, reverseT = NULL)

PB_Angkarsklubb_Plot <- plot(PB_ros_Angkarsklubb)






par(mfrow = c(2,3))
plot(PB_ros_Fladen)
plot(PB_ros_Harufjarden)
plot(PB_ros_Landsort)
plot(PB_ros_Utlangan)
plot(PB_ros_Vaderoarna)
plot(PB_ros_Angkarsklubb)
mtext("Title for Two Plots", outer = TRUE, cex = 1.5)










NI_Fladen <- List_each_LOC[[1]] %>% filter(SPECIES == "Herring") %>% select(NI) %>% mutate(cens = NI < 0)

NI_ros_Fladen <- cenros(log(abs(NI_Fladen[['NI']])), NI_Fladen[['cens']], forwardT= NULL , reverseT = NULL)

NI_Fladen_Plot <- plot(NI_ros_Fladen)


NI_Harufjarden <- List_each_LOC[[2]] %>% filter(SPECIES == "Herring") %>% select(NI) %>% mutate(cens = NI < 0)

NI_ros_Harufjarden <- cenros(log(abs(NI_Harufjarden[['NI']])), NI_Harufjarden[['cens']], forwardT= NULL, reverseT = NULL)

NI_Harufjarden_Plot <- plot(NI_ros_Harufjarden)


NI_Landsort <- List_each_LOC[[3]] %>% filter(SPECIES == "Herring") %>% select(NI) %>% mutate(cens = NI < 0)

NI_ros_Landsort <- cenros(log(abs(NI_Landsort[['NI']])), NI_Landsort[['cens']], forwardT= NULL, reverseT = NULL)


NI_Utlangan <- List_each_LOC[[4]] %>% filter(SPECIES == "Herring") %>% select(NI) %>% mutate(cens = NI < 0)

NI_ros_Utlangan <- cenros(log(abs(NI_Utlangan[['NI']])), NI_Utlangan[['cens']], forwardT= NULL, reverseT = NULL)




NI_Vaderoarna<- List_each_LOC[[5]] %>% filter(SPECIES == "Herring") %>% select(NI) %>% mutate(cens = NI < 0)

NI_ros_Vaderoarna <- cenros(log(abs(NI_Vaderoarna[['NI']])), NI_Vaderoarna[['cens']], forwardT= NULL, reverseT = NULL)

NI_Vaderoarna_Plot <- plot(NI_ros_Vaderoarna)


NI_Angkarsklubb<- List_each_LOC[[6]] %>% filter(SPECIES == "Herring") %>% select(NI) %>% mutate(cens = NI < 0)

NI_ros_Angkarsklubb <- cenros(log(abs(NI_Angkarsklubb[['NI']])), NI_Angkarsklubb[['cens']], forwardT = NULL, reverseT = NULL)

NI_Angkarsklubb_Plot <- plot(NI_ros_Angkarsklubb)



pdf("NI_ros_plots.pdf")
par(mfrow = c(2,3),  mai = c(1.2, 0.4, 0.1, 0.1))
plot(NI_ros_Fladen)
plot(NI_ros_Harufjarden)
plot(NI_ros_Landsort)
plot(NI_ros_Utlangan)
plot(NI_ros_Vaderoarna)
plot(NI_ros_Angkarsklubb)
dev.off()




CR_Fladen <- List_each_LOC[[1]] %>% filter(SPECIES == "Herring") %>% select(CR) %>% mutate(cens = CR < 0)

CR_ros_Fladen <- cenros(log(abs(CR_Fladen[['CR']])), CR_Fladen[['cens']], forwardT= NULL , reverseT = NULL)

CR_Fladen_Plot <- plot(CR_ros_Fladen)


CR_Harufjarden <- List_each_LOC[[2]] %>% filter(SPECIES == "Herring") %>% select(CR) %>% mutate(cens = CR < 0)

CR_ros_Harufjarden <- cenros(log(abs(CR_Harufjarden[['CR']])), CR_Harufjarden[['cens']], forwardT= NULL, reverseT = NULL)

CR_Harufjarden_Plot <- plot(CR_ros_Harufjarden)


CR_Landsort <- List_each_LOC[[3]] %>% filter(SPECIES == "Herring") %>% select(CR) %>% mutate(cens = CR < 0)

CR_ros_Landsort <- cenros(log(abs(CR_Landsort[['CR']])), CR_Landsort[['cens']], forwardT= NULL, reverseT = NULL)


CR_Utlangan <- List_each_LOC[[4]] %>% filter(SPECIES == "Herring") %>% select(CR) %>% mutate(cens = CR < 0)

CR_ros_Utlangan <- cenros(log(abs(CR_Utlangan[['CR']])), CR_Utlangan[['cens']], forwardT= NULL, reverseT = NULL)




CR_Vaderoarna<- List_each_LOC[[5]] %>% filter(SPECIES == "Herring") %>% select(CR) %>% mutate(cens = CR < 0)

CR_ros_Vaderoarna <- cenros(log(abs(CR_Vaderoarna[['CR']])), CR_Vaderoarna[['cens']], forwardT= NULL, reverseT = NULL)

CR_Vaderoarna_Plot <- plot(CR_ros_Vaderoarna)


CR_Angkarsklubb<- List_each_LOC[[6]] %>% filter(SPECIES == "Herring") %>% select(CR) %>% mutate(cens = CR < 0)

CR_ros_Angkarsklubb <- cenros(log(abs(CR_Angkarsklubb[['CR']])), CR_Angkarsklubb[['cens']], forwardT = NULL, reverseT = NULL)

CR_Angkarsklubb_Plot <- plot(CR_ros_Angkarsklubb)



List_each_LOC[[1]] %>% 
  filter(SPECIES == "Herring") %>% 
  select(YEAR, PB) %>% 
  mutate(PB = log(abs(PB))) %>% 
  group_by(YEAR) %>% 
  summarise(Variance = sd(PB))



List_each_LOC[[1]] %>% count(YEAR) %>% nrow()  



std_matrix_all <- matrix(ncol = 30,  nrow = 12)

i = 1
k = 1
while(k<13){
  i=1
  while(i<30){
  data <- List_all_LOC[[i]] %>%
    filter(SPECIES == "Herring") %>%
    select(YEAR, CR) %>% 
    mutate(cens = CR < 0) %>% 
    filter(YEAR == 2006 + k) %>% 
    mutate(CR = abs(CR))  
    stats <- cenmle(data$CR, data$cens, dist = "lognormal") 
    std_matrix_all[k,i] <- sd(stats)^2 
    i = i + 1
  }
  k = k+1
}


List_each_LOC[[6]]


List_all_LOC <- split(metals, f = metals$LOC)

std_PB_yearly <- as.data.frame(std_matrix) %>% 
  rename(Fladen = V1)%>% 
  rename(Harufjärden = V2)%>% 
  rename(Landsort = V3)%>% 
  rename(Utlängan = V4)%>% 
  rename(Väderöarna = V5)%>% 
  rename(Ängskärsklubb = V6)
std_NI_yearly <- as.data.frame(std_matrix_NI)%>% 
  rename(Fladen = V1)%>% 
  rename(Harufjärden = V2)%>% 
  rename(Landsort = V3)%>% 
  rename(Utlängan = V4)%>% 
  rename(Väderöarna = V5)%>% 
  rename(Ängskärsklubb = V6)

std_CR_yearly <- as.data.frame(std_matrix_CR) %>% 
  rename(Fladen = V1)%>% 
  rename(Harufjärden = V2)%>% 
  rename(Landsort = V3)%>% 
  rename(Utlängan = V4)%>% 
  rename(Väderöarna = V5)%>% 
  rename(Ängskärsklubb = V6)

sqrt(std_PB_yearly)


sqrt(std_CR_yearly)


CR_utlangan_eight <- List_each_LOC[[4]] %>% filter(YEAR == 2008) %>% select(CR) %>% mutate(cens = CR < 0) %>% mutate(CR = abs(CR))


cenmle(CR_utlangan_eight$CR, CR_utlangan_eight$cens)


std_matrix_all %>% as.data.frame()


metals_many_obs_herring %>% 
  mutate(CR = ifelse(CR < 0, log(abs(CR)/sqrt(2)), log(abs(CR)))) %>% 
  group_by(YEAR, LOC) %>%
  summarise(variance = sd(CR)^2)


as.data.frame(std_matrix_all)


plot(PB_ros_Landsort)


PB_Landsort
List_each_LOC[[2]] %>% filter(SPECIES == "Herring") %>% select(PB) %>% mutate(cens = PB < 0) %>% mutate(PB = log(abs(PB)))


PB_Fladen

PB_Landsort %>% mutate(PB = log(abs(PB)))



qqnorm(PB_ros_Landsort$)

PB_Landsort %>% mutate(PB = log(abs(PB)))


qqnorm(log(abs(PB_Landsort$PB)))
qqline(log(abs(PB_Landsort$PB)))

PB_Landsort %>% mutate(PB = log(abs(PB)))


CR_Fladen %>% mutate(CR = log(abs(CR)))

metals %>% select(YEAR) %>% unique()


metals %>% 
  filter(LOC == "Ängskärsklubb") %>% 
  drop_na(PB) %>% 
  mutate(PB = abs(PB)) %>% 
  summarise(mean(PB))

metals

metals %>% select(LOC) %>% unique()


asd <- metals %>% filter(LOC == "Fladen") %>% filter(SPECIES == "Herring") %>%
  filter(YEAR == 2009) %>% select(PB)

censoror <- asd$PB < 0

cenmle(abs(asd$PB), censoror, dist = "lognormal")


metals %>% filter(LOC == "Harufjärden") %>% filter(SPECIES == "Herring") %>% 
  group_by(YEAR) %>% drop_na(NI) %>% 
  mutate(NI = (abs(NI))) %>% 
  summarise(sd = sd(NI))


rlnorm(11, 0.00001, 0.0000447)


metals %>% filter(LOC == "Landsort") %>% filter(SPECIES == "Herring") %>% group_by(YEAR) %>% mutate(PB = (abs(PB))) %>% summarise(sd = sd(PB)) 


qqnorm(log(predictors))
qqline(log(predictors))
k=1
while(k<13){
  asd <- metals %>% filter(LOC == "Harufjärden") %>% drop_na(NI) %>%  filter(SPECIES == "Herring") %>%
    filter(YEAR == 2006+k) %>% select(PB)
  censoror <- asd$PB < 0
  stats <- cenmle((abs(asd$PB)), censoror, dist = "lognormal")
  print(sd(stats))
  k=k+1
}
```







```{r}

load("Simulations/slope1.01_res0.5_randomLOW.Rda")
load("Simulations/slope1.01_res0.5_randomHIGH.Rda")
load("Simulations/slope1.05_res0.5_randomLOW.Rda")
load("Simulations/slope1.05_res0.5_randomHIGH.Rda")

Completed_df_2 <- full_join(df_1.01_0.5_LOW,df_1.01_0.5_HIGH) %>%
  full_join(df_1.05_0.5_LOW) %>% 
  full_join(df_1.05_0.5_HIGH)  %>% 
  mutate(CI_Lower = Beta - `Beta sd`*1.96) %>% 
  mutate(CI_Upper = Beta + `Beta sd`*1.96) %>% 
  mutate(Coverage = ifelse(Slope>CI_Lower & Slope < CI_Upper, 1, 0 ))

save(Completed_df_2, file = "Completed_df_2.Rda")
  


with_bias_2 <- Completed_df_2 %>% 
  filter(Method != "True") %>% 
  mutate(diff = (Beta-Slope)^2) %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise(bias = mean(diff)) %>% 
  ungroup

with_coverage <- Completed_df_2 %>% 
  filter(Method != "True") %>% 
  mutate(diff = (Beta-Slope)^2) %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise(coverage = mean(Coverage))

bias_coverage <- with_bias %>% 
  mutate(Coverage = with_coverage$coverage)





Variances <- Completed_df_2 %>% 
  filter(Method != "True") %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise(Variance = sd(Beta)^2)

bias_coverage



All_Summary_Stats_2 <- bias_coverage %>% 
  inner_join(Variances, by = c('Limit fraction', 'Slope', 'Std', 'Random Effects', 'Method')) %>% 
  mutate(MSE = bias + Variance) %>% 
  mutate("Standard Error" = with_standard_error_2$`Standard Error`)

save(All_Summary_Stats_2, file = "Rdata_Files/All_Summary_Stats_2.Rda")


with_standard_error_2 <- Completed_df_2 %>% 
  filter(Method != "True") %>% 
  mutate(diff = (Beta-Slope)^2) %>% 
  group_by(`Limit fraction`, Slope, Std, `Random Effects`, Method) %>% 
  summarise("Standard Error" = sd(diff)/10) %>% 
  ungroup 
```



```{r}
Haru <- metals %>% filter(LOC == "Harufjärden") %>% filter(SPECIES == "Herring") %>% arrange(desc(NI)) %>% slice(-1) %>% drop_na(NI)


      yL <- log(abs(Haru$NI))
    cens <-Haru$NI < 0
    X <- cbind(rep_len(1,length(Haru$YEAR)), Haru$YEAR)
    Z <- matrix(rep_len(1,length(Haru$YEAR)), ncol=1)
    cluster <- as.numeric(factor(Haru$YEAR))
    fitted <- lmec(yL, cens, X, Z, cluster, maxstep = 20, method = "ML")
    
    
    
  metals %>% filter(LOC=="Harufjärden") %>% filter(SPECIES == "Herring") %>% select(PB) %>% mutate(cens = PB<0) %>% mutate(logPB = log(abs(PB))) %>% arrange(desc(PB))
  
  

```



```{r}
load("Simulations/slope1.01_res0.05_randomLOW_NEG.Rda")


library(tidyverse)


df_1.01_0.05_LOW_neg
betas_neg_0.05_LOW <- df_1.01_0.05_LOW_neg %>% filter(Method != "True") %>% mutate(Slope_Perc = "-1%")

tobit_betas_individual_low_neg <- betas_neg_0.05_LOW %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.05)


museum_betas_individual_low_neg <- betas_neg_0.05_LOW %>% 
  filter(Method == "Museum") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.05)

betas_spread_individual_low_neg <- tobit_betas_individual_low_neg %>% 
  mutate(Museum_Beta = museum_betas_individual_low_neg$Beta)


  facet_grid( ~ `Limit fraction`) +
  geom_point(alpha = 0.35) + 
   geom_hline(data = data.frame(Slope_Perc="-1%", y=-log(1.01)), mapping=aes(yintercept=y)) +
   geom_vline(data = data.frame(Slope_Perc="-1%", x=-log(1.01)), mapping=aes(xintercept=x)) +
  labs(caption = "Figure 3: Plotting the estimated slopes for the Museum model
  and Tobit model against eachother having the variance of individual specimens set to medium.
  The vertical and horizontal lines correspond to the true value of the slope.")



df_1.01_0.05_LOW_neg %>% group_by(`Limit fraction`, Method) %>% mutate(bias = (Beta-Slope)^2) %>% summarise(bias = mean(bias))


as.data.frame(dataset_censored) %>% mutate(cens = dataset_censored<0) %>% summarise(mean=mean(cens))

```


```{r}
df_1.1_0.5_LOW_neg <- df_1.1_0.5_LOW %>% filter(Method != "True") %>% na.omit() %>% filter(Slope < 0)

save(df_1.1_0.5_LOW_neg, file = "df_1.1_0.5_LOW_neg.Rda")

load("df_1.1_0.5_LOW_neg.Rda")

df_1.1_0.5_LOW_neg %>% mutate(bias = (Beta-Slope)^2) %>%  group_by(Method) %>% summarise(bias = mean(bias))



hejhej <- Completed_df %>% mutate(bias_sq = (Beta-Slope)^2) %>% filter(`Random Effects` == "High", Std == 1.4, `Limit fraction` == 0.6, Slope > 0.01, Method == "Tobit")


hejhej %>% ggplot(aes(x=bias_sq)) + geom_histogram()


data <- metals %>% 
  filter(LOC == "Utlängan") %>% 
  filter(SPECIES == "Herring") %>%
    select(YEAR, NI) %>% 
  na.omit() %>% 
    mutate(cens = NI < 0) %>% 
    mutate(NI = abs(NI))  
    stats <- cenmle(((data$NI)), data$cens, dist = "lognormal") 
    
    0.04
    
data %>% na.omit() %>% summarise(var = sd(log(NI))^2)

df_cens_1.05



load("df_cens_1.01.Rda")
load("df_cens_1.05.Rda")
load("df_cens_1.1.Rda")


df_cens_1.01
df_cens_1.05
df_cens_1.1


nick <- metals %>% filter(LOC == "Fladen") %>% 
  filter(SPECIES == "Herring") %>% 
  select(NI) %>% 
  na.omit()

cenmle(abs(nick$NI), nick$NI<0, dist = "lognormal")


(0.0039)/(log(1.05))






load("cens_df_1.01_low.Rda")
load("cens_df_1.05_low.Rda")
load("cens_df_1.1_low.Rda")



load("df_80_1.05_0.05.Rda")
load("df_80_1.1_0.05.Rda")
load("df_80_1.05_0.5.Rda")
load("df_80_1.1_0.5.Rda")

```



