---
title: "testtest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(NADA)
library(tidyverse)
library(lmec)
```

```{r}
metals <- read_csv("../metals.csv")

#Tar fram platser med många observationer för Herring
Location_many_observations_herring <- metals %>% 
  filter(SPECIES == "Herring") %>% 
  group_by(LOC) %>% 
  count(YEAR) %>% 
  summarise(obs = sum(n)) %>% 
  filter(obs>100)

#Fltrerar dataset så endast platser ovan är med
metals_many_obs_herring <- metals %>% 
  filter(LOC %in% Location_many_observations_herring[[1]])

#Delar upp datasettet i ett dataset per plats
List_each_LOC <- split(metals_many_obs_herring, f = metals_many_obs_herring$LOC)





#Skapar tom matris för att tillsätta resultat från nedan
Betas_NI_Herring <- matrix(nrow = length(List_each_LOC), ncol = 7)

i = 1
Metal = 'NI'

#Loopar över varje plats och tar fram skattad lutning, antal år, antal observationer, andel censurerat och varians
while(i<length(List_each_LOC)+1) {
  df <- List_each_LOC[[i]] %>% drop_na(Metal)
  N <- length(df[[Metal]])
  Observations <- log(abs(df[[Metal]]))
  Censoring_Indicator <- df[[Metal]] < 0
  X <- cbind(rep_len(1,N), df[['YEAR']])
  Z <- matrix(rep_len(1,N), ncol=1)
  cluster <- as.numeric(factor(df[['YEAR']]))
  fitted <- lmec(Observations, Censoring_Indicator, X, Z, cluster, maxstep = 20, method = "ML")
  
  Betas_NI_Herring[i,1] <- df[['LOC']] %>% unique()
  Betas_NI_Herring[i,2] <- fitted$beta[2]
  Betas_NI_Herring[i,3] <- fitted$varFix[[2,2]]
  Betas_NI_Herring[i,4] <- mean(Censoring_Indicator)
  Betas_NI_Herring[i,5] <- df[['YEAR']] %>% unique() %>% length()
  Betas_NI_Herring[i,6] <- N
  Betas_NI_Herring[i,7] <- sd(cenmle(exp(Observations), Censoring_Indicator, dist = "lognormal" ))
  i = i+1
}


df_NI_Herring <- Betas_NI_Herring %>% 
  as.data.frame() %>% 
  rename(Location = V1) %>% 
  rename(Beta = V2) %>% 
  rename('Var(Beta)' = V3) %>% 
  rename("%Censored" = V4) %>% 
  rename("# of Years" = V5) %>% 
  rename("# of Observations" = V6) %>% 
  rename("Variance of Location" = V7) %>% 
  mutate(Beta = (as.numeric(as.character(Beta)))) %>% 
  mutate(`%Censored` = (as.numeric(as.character(`%Censored`)))*100)

save(df_NI_Herring, file = "df_NI_Herring.Rda")
```

