---
title: "Applications"
author: "Anton Holm"
date: '2020-04-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(NADA)
```

```{r}
### Delar upp LOCATIONS

metals <- read_csv("../metals.csv")

#Tar fram platser med många observationer för Herring
Location_many_observations_herring <- metals %>% 
  filter(SPECIES == "Herring") %>% 
  group_by(LOC) %>% 
  count(YEAR) %>% 
  summarise(obs = sum(n)) %>% 
  filter(obs>100)

#Fltrerar dataset så endast platser ovan är med
metals_many_obs_herring <- metals %>% 
  filter(LOC %in% Location_many_observations_herring[[1]])

#Delar upp datasettet i ett dataset per plats
List_each_LOC <- split(metals_many_obs_herring, f = metals_many_obs_herring$LOC)
```


```{r}
#Utför analys med Tobit Modellen

#Skapar tom matris för att tillsätta resultat från nedan
Betas_NI_Herring <- matrix(nrow = length(List_each_LOC), ncol = 7)

i = 1
Metal = 'CR'

#Loopar över varje plats och tar fram skattad lutning, antal år, antal observationer, andel censurerat och varians
while(i<length(List_each_LOC)+1) {
  df <- List_each_LOC[[i]] %>% drop_na(Metal)
  N <- length(df[[Metal]])
  Observations <- log(abs(df[[Metal]]))
  Censoring_Indicator <- df[[Metal]] < 0
  X <- cbind(rep_len(1,N), df[['YEAR']])
  Z <- matrix(rep_len(1,N), ncol=1)
  cluster <- as.numeric(factor(df[['YEAR']]))
  fitted <- lmec(Observations, Censoring_Indicator, X, Z, cluster, maxstep = 20, method = "ML")
  
  Betas_NI_Herring[i,1] <- df[['LOC']] %>% unique()
  Betas_NI_Herring[i,2] <- fitted$beta[2]
  Betas_NI_Herring[i,3] <- fitted$varFix[[2,2]]
  Betas_NI_Herring[i,4] <- mean(Censoring_Indicator)
  Betas_NI_Herring[i,5] <- df[['YEAR']] %>% unique() %>% length()
  Betas_NI_Herring[i,6] <- N
  Betas_NI_Herring[i,7] <- sd(cenmle(exp(Observations), Censoring_Indicator, dist = "lognormal" ))
  i = i+1
}


df_PB_Herring <- Betas_PB_Herring %>% 
  as.data.frame() %>% 
  rename(Location = V1) %>% 
  rename(Beta = V2) %>% 
  rename('Var(Beta)' = V3) %>% 
  rename("%Censored" = V4) %>% 
  rename("# of Years" = V5) %>% 
  rename("# of Observations" = V6) %>% 
  rename("Std of Location" = V7) %>% 
  mutate(Beta = (as.numeric(as.character(Beta)))) %>% 
  mutate(`%Censored` = (as.numeric(as.character(`%Censored`)))*100) %>% 
  mutate(`Std of Location` = sqrt(as.numeric(as.character(`Std of Location`))))

save(df_PB_Herring, file = "df_PB_Herring.Rda")


df_PB_Herring %>% mutate(Beta = exp(Beta))


List_each_LOC[[2]] %>% select(PB)



df_PB_Herring <- df_PB_Herring %>% mutate(`Variance of Location` = sqrt(as.numeric(as.character(`Variance of Location`)))) %>% rename("Std of Location" = "Variance of Location")

df_PB_Herring
df_NI_Herring
df_CR_Herring

df_PB_Herring <- df_PB_Herring %>% mutate(`Std of Location` = (`Std of Location`)^2)
df_NI_Herring <- df_NI_Herring %>% mutate(`Std of Location` = (`Std of Location`)^2)
df_CR_Herring <- df_CR_Herring %>% mutate(`Std of Location` = (`Std of Location`)^2)

```


```{r}
#Skapar plottar för log-normal antagande


  pdf("PB_ros_plots.pdf")
  par(mfrow = c(2,3),  mai = c(0.7, 0.4, 0.7, 0.1))
  plot(PB_ros_Fladen, sub = "Fladen: PB")
  plot(PB_ros_Harufjarden, sub = "Harufjärden: PB")
  plot(PB_ros_Landsort, sub = "Landsort: PB")
  plot(PB_ros_Utlangan, sub = "Utlängan: PB")
  plot(PB_ros_Vaderoarna, sub = "Värderöarna: PB")
  plot(PB_ros_Angkarsklubb, sub = "Ängkärsklub: PB")
  dev.off()
  
  
pdf("NI_ros_plots.pdf")
par(mfrow = c(2,3),  mai = c(0.7, 0.4, 0.7, 0.1))
plot(NI_ros_Fladen, sub = "Fladen: NI")
plot(NI_ros_Harufjarden, sub = "Harufjärden: NI")
plot(NI_ros_Landsort, sub = "Landsort: NI")
plot(NI_ros_Utlangan, sub = "Utlängan: NI")
plot(NI_ros_Vaderoarna, sub = "Värderöarna: NI")
plot(NI_ros_Angkarsklubb, sub = "Ängkärsklub: NI")
dev.off()



pdf("CR_ros_plots.pdf")
par(mfrow = c(2,3),  mai = c(0.7, 0.4, 0.7, 0.1))
plot(CR_ros_Fladen, sub = "Fladen: CR")
plot(CR_ros_Harufjarden, sub = "Harufjärden: CR")
plot(CR_ros_Landsort, sub = "Landsort: CR")
plot(CR_ros_Utlangan, sub = "Utlängan: CR")
plot(CR_ros_Vaderoarna, sub = "Värderöarna: CR")
plot(CR_ros_Angkarsklubb, sub = "Ängkärsklub: CR")
dev.off()




  par(mfrow = c(2,3),  mai = c(0.7, 0.4, 0.7, 0.1))
  plot(PB_ros_Fladen, sub = "Fladen")
  plot(PB_ros_Harufjarden, sub = "Harufjärden")
  plot(PB_ros_Landsort, sub = "Landsort")
  plot(PB_ros_Utlangan, sub = "Utlängan")
  plot(PB_ros_Vaderoarna, sub = "Värderöarna")
  plot(PB_ros_Angkarsklubb, sub = "Ängkärsklub")
```


```{r}
#Utför analys med substitution

Betas_CR_Herring_Museum <- matrix(nrow = length(List_each_LOC), ncol = 2)

i = 1
Metal = 'CR'


while(i<length(List_each_LOC)+1) {
  df <- List_each_LOC[[i]] %>% drop_na(Metal) %>% 
    filter(SPECIES == "Herring") %>% 
    select(YEAR, CR) %>% 
    mutate(CR = ifelse(CR < 0, log(abs(CR)/sqrt(2)), log(abs(CR))))
    stats <- summary(lm(CR ~ YEAR, data = df))
    Betas_CR_Herring_Museum[i,1] <- stats$coefficients[2,1]
    Betas_CR_Herring_Museum[i,2] <- stats$coefficients[2,2]
    i = i + 1
  
}

PB_Museum_df <- Betas_PB_Herring_Museum %>% 
  as.data.frame() %>% 
  rename(Museum_Beta = V1) %>% 
  rename(Museum_Beta_Std = V2)


NI_Museum_df <- Betas_NI_Herring_Museum %>% 
  as.data.frame() %>% 
  rename(Museum_Beta = V1) %>% 
  rename(Museum_Beta_Std = V2)


CR_Museum_df <- Betas_CR_Herring_Museum %>% 
  as.data.frame() %>% 
  rename(Museum_Beta = V1) %>% 
  rename(Museum_Beta_Std = V2)

full_PB_df <- df_PB_Herring %>% 
  mutate(Museum_Beta = PB_Museum_df[[1]]) %>% 
  mutate(Museum_Beta_STD = PB_Museum_df[[2]])

full_NI_df <- df_NI_Herring %>% 
  mutate(Museum_Beta = NI_Museum_df[[1]]) %>% 
  mutate(Museum_Beta_STD = NI_Museum_df[[2]])

full_CR_df <- df_CR_Herring %>% 
  mutate(Museum_Beta = CR_Museum_df[[1]]) %>% 
  mutate(Museum_Beta_STD = CR_Museum_df[[2]])


for_thesis_PB_df <- full_PB_df %>% 
  select(Location, Beta, `Var(Beta)`, Museum_Beta, Museum_Beta_STD, `%Censored`, `Std of Location`) %>% 
  mutate(`Var(Beta)` = as.numeric(as.character(`Var(Beta)`))) %>% 
  mutate(`Var(Beta)` = sqrt(`Var(Beta)`)) %>% 
  rename("Tobit Beta Std" = `Var(Beta)`) %>% 
  mutate_if(is.numeric, round, digits = 4)
  
for_thesis_PB_df_2 <- for_thesis_PB_df %>% 
  mutate(Museum_Beta = round(medel_PB_df$V1, 4)) %>% 
  mutate(Museum_Beta_STD = round(medel_PB_df$V2, 4)) %>% 
  mutate(p_sub = round(2*pt(-abs(Museum_Beta/Museum_Beta_STD), df = 9),4)) %>% 
  mutate(p_lmmc = round(2*pt(-abs(Beta/`Tobit Beta Std`), df = 129),4))
  

for_thesis_NI_df <- full_NI_df %>% 
  select(Location, Beta, `Var(Beta)`, Museum_Beta, Museum_Beta_STD, `%Censored`, `Std of Location`) %>% 
  mutate(`Var(Beta)` = as.numeric(as.character(`Var(Beta)`))) %>% 
  mutate(`Var(Beta)` = sqrt(`Var(Beta)`)) %>% 
  rename("Tobit Beta Std" = `Var(Beta)`) %>% 
  mutate_if(is.numeric, round, digits = 4) %>% 
  rename("LMMC Estimate" = Beta)

for_thesis_NI_df_2 <- for_thesis_NI_df %>% 
  mutate(Museum_Beta = round(medel_NI_df$V1, 4)) %>% 
  mutate(Museum_Beta_STD = round(medel_NI_df$V2, 4))%>% 
  mutate(p_sub = round(2*pt(-abs(Museum_Beta/Museum_Beta_STD), df = 9),4)) %>% 
  mutate(p_lmmc = round(2*pt(-abs(Beta/`Tobit Beta Std`), df = 129),4))

for_thesis_CR_df <- full_CR_df %>% 
  select(Location, Beta, `Var(Beta)`, Museum_Beta, Museum_Beta_STD, `%Censored`, `Std of Location`) %>% 
  mutate(`Var(Beta)` = as.numeric(as.character(`Var(Beta)`))) %>% 
  mutate(`Var(Beta)` = sqrt(`Var(Beta)`)) %>% 
  rename("Tobit Beta Std" = `Var(Beta)`) %>% 
  mutate_if(is.numeric, round, digits = 4)

for_thesis_CR_df_2 <- for_thesis_CR_df %>% 
  mutate(Museum_Beta = round(medel_CR_df$V1,4)) %>% 
  mutate(Museum_Beta_STD =round(medel_CR_df$V2,4))%>% 
  mutate(p_sub = round(2*pt(-abs(Museum_Beta/Museum_Beta_STD), df = 9),4)) %>% 
  mutate(p_lmmc = round(2*pt(-abs(Beta/`Tobit Beta Std`), df = 129),4))

save(for_thesis_PB_df_2, for_thesis_NI_df_2, for_thesis_CR_df_2, file = "../Rdata_Files/substitution_df_application_medelvarde.Rda")

load("../Rdata_Files/substitution_df_application.Rda")

colnames(for_thesis_CR_df_2) <- c("Location", "$\\hat{\\beta}_{LMMC}$", "sd($\\hat{\\beta}_{LMMC}$)", "$\\hat{\\beta}_{Sub}$", "sd($\\hat{\\beta}_{Sub}$)", "\\% Censored", "Sd of Location $^*$", "$p_{_{Sub}}$", "$p_{_{LMMC}}$")

colnames(for_thesis_NI_df_2) <- c("Location", "$\\hat{\\beta}_{LMMC}$", "sd($\\hat{\\beta}_{LMMC}$)", "$\\hat{\\beta}_{Sub}$", "sd($\\hat{\\beta}_{Sub}$)", "\\% Censored", "Sd of Location", "$p_{_{Sub}}$", "$p_{_{LMMC}}$")

colnames(for_thesis_PB_df_2) <- c("Location", "$\\hat{\\beta}_{LMMC}$", "sd($\\hat{\\beta}_{LMMC}$)", "$\\hat{\\beta}_{Sub}$", "sd($\\hat{\\beta}_{Sub}$)", "\\% Censored", "Sd of Location", "$p_{_{Sub}}$", "$p_{_{LMMC}}$")

thesis_CR_Table <- kable(for_thesis_CR_df_2, booktabs=T, escape=F, format = "latex", align = "l", caption = "Results of application of both models on data for chromium concentrations in herring (Estimated slope on Log-Scale)") %>% 
column_spec(1, bold=T) %>% footnote(general = "Due to high proportion of censoring the standard deviations are unreliable.", general_title = "*", footnote_as_chunk = TRUE, title_format = c("italic")) %>% 
  kable_styling(full_width=F) %>% 
  kable_styling(latex_options="scale_down")

thesis_NI_Table <- kable(for_thesis_NI_df_2, booktabs=T, escape=F, format = "latex", align = "l", caption = "Results of application of both models on data for nickel concentrations in herring (Estimated slope on Log-Scale)") %>% 
column_spec(1, bold=T) %>% 
  kable_styling(latex_options="scale_down")

thesis_PB_Table <- kable(for_thesis_PB_df_2, booktabs=T, escape=F, format = "latex", align = "l", caption = "Results of application of both models on data for lead concentrations in herring (Estimated slope on Log-Scale)") %>% 
column_spec(1, bold=T) %>% 
  kable_styling(latex_options="scale_down")

save(thesis_CR_Table, thesis_NI_Table, thesis_PB_Table, file = "../Rdata_Files/tables_application.Rda")


```



```{r}
data <- List_each_LOC[[6]]%>% 
  filter(SPECIES == "Herring") %>% 
  drop_na(PB)


medel_chrom <- matrix(nrow = 6, ncol = 2)
for(i in 1:length(List_each_LOC)){
  data <- List_each_LOC[[i]]
  medel <- data %>% 
  filter(SPECIES == "Herring") %>% 
  drop_na(PB) %>%
  mutate(PB = ifelse(PB<0, log(abs(PB)/sqrt(2)), log(abs(PB)))) %>% 
  group_by(YEAR) %>% 
  summarise(PB = mean(PB))

  summary <- summary(lm(medel$PB ~ medel$YEAR))
  medel_chrom[i,1] <- summary$coefficients[2,1]
  medel_chrom[i,2] <- summary$coefficients[2,2]
}


medel_PB_df <- medel_lead %>% as.data.frame()
medel_NI_df <- medel_nickel %>% as.data.frame()
medel_CR_df <- medel_chrom %>% as.data.frame()


for_thesis_PB_df %>% mutate(Museum_Beta = medel_PB_df$V1)


summary(lm(medel$CR~medel$YEAR))

medel <- data %>% 
  drop_na(CR) %>%
  mutate(CR = log(abs(CR)))

yl <- medel$CR
    X <- cbind(rep_len(1,length(medel$YEAR)), medel$YEAR )
cens <- (data$CR) < 0
cluster <- as.numeric(factor(medel$YEAR))
Z <- matrix(rep_len(1,length(medel$YEAR)), ncol=1)

sum <- lmec(yl, cens, X, Z, cluster, maxstep = 20, method = "ML")

summary(sum)




2*pt(-0.029627654/0.02274325, df = 9)

pt(abs(-1), df = 130)

for_thesis_PB_df_2

0.4732



List_each_LOC[[6]] %>% select(YEAR) %>% unique() %>% count()


List_each_LOC[[6]] %>% filter(SPECIES == "Herring")
```
