---
title: "Plotting_Betas"
author: "Anton Holm"
date: '2020-04-16'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
```

```{r}
load("../Rdata_Files/Completed_df.Rda")
load("../Completed_df_2.Rda")
Completed_df_New <- Completed_df %>% full_join(Completed_df_2) %>%  mutate(`Random Effects` = replace(`Random Effects`, `Random Effects` == "HIGH", "High"))
save(Completed_df_New, file = "../Rdata_Files/Completed_df_New.Rda")


betas <- Completed_df_New %>% filter(Method != "True") %>% mutate(Slope_Perc = ifelse(Slope < 0.01, "1% yearly increase", "5% yearly increase")) %>% 
  mutate(`Limit fraction` = ifelse(`Limit fraction` == 0.3, "30% censoring", "60% Censoring"))
```

```{r}
tobit_betas_individual_high <- betas %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method)) %>% 
  filter(Std == 1.4)


museum_betas_individual_high <- betas %>% 
  filter(Method == "Museum") %>% 
  select(-(Method)) %>% 
  filter(Std == 1.4)

betas_spread_individual_high <- tobit_betas_individual_high %>% 
  mutate(Museum_Beta = museum_betas_individual_high$Beta)


Plot_High_Individual_Variance <- betas_spread_individual_high %>% ggplot(aes(x=Beta, y=Museum_Beta, col = `Random Effects`, shape = `Random Effects`)) +
  facet_grid(Slope_Perc ~ `Limit fraction`) +
  geom_point(alpha = 0.35) + 
  theme_minimal() +
  theme(plot.caption=element_text(hjust = 0), legend.background = element_rect(color = "black", 
    fill = NA, size =0.5, linetype = "solid"),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5),legend.title = element_text(color = "black", size = 8), legend.position = "top")+ 
   geom_hline(data = data.frame(Slope_Perc="1% yearly increase", y=log(1.01)), mapping=aes(yintercept=y)) +
   geom_vline(data = data.frame(Slope_Perc="1% yearly increase", x=log(1.01)), mapping=aes(xintercept=x)) +
  geom_hline(data = data.frame(Slope_Perc="5% yearly increase", y=log(1.05)), mapping=aes(yintercept=y))+
   geom_vline(data = data.frame(Slope_Perc="5% yearly increase", x=log(1.05)), mapping=aes(xintercept=x)) +
  labs(caption = "Figure 5: Plotting the estimated slopes for the substitution method and the LMMC model against eachother having the variance of individual specimens
set to high. The vertical and horizontal lines correspond to the true value of the slope.",
  x = 'Estimates of the LMMC Model', y = 'Estimates from Substitution')

save(Plot_High_Individual_Variance, file = "../Rdata_Files/Plot_High_Individual_Variance.Rda")





tobit_betas_individual_low <- betas %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.05)


museum_betas_individual_low <- betas %>% 
  filter(Method == "Museum") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.05)

betas_spread_individual_low <- tobit_betas_individual_low %>% 
  mutate(Museum_Beta = museum_betas_individual_low$Beta)


Plot_Low_Individual_Variance <- betas_spread_individual_low %>% ggplot(aes(x=Beta, y=Museum_Beta, col = `Random Effects`, shape = `Random Effects`)) +
  facet_grid(Slope_Perc ~ `Limit fraction`) +
  geom_point(alpha = 0.35) + 
  theme_minimal() +
  theme(plot.caption=element_text(hjust = 0), legend.background = element_rect(color = "black", 
    fill = NA, size =0.5, linetype = "solid"),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5),legend.title = element_text(color = "black", size = 8), legend.position = "top")+ 
   geom_hline(data = data.frame(Slope_Perc="1% yearly increase", y=log(1.01)), mapping=aes(yintercept=y)) +
   geom_vline(data = data.frame(Slope_Perc="1% yearly increase", x=log(1.01)), mapping=aes(xintercept=x)) +
  geom_hline(data = data.frame(Slope_Perc="5% yearly increase", y=log(1.05)), mapping=aes(yintercept=y))+
   geom_vline(data = data.frame(Slope_Perc="5% yearly increase", x=log(1.05)), mapping=aes(xintercept=x)) +
  labs(caption = "Figure 3: Plotting the estimated slopes for the Museum model and Tobit model against eachother having the variance of individual specimens 
set to low. The vertical and horizontal lines correspond to the true value of the slope.",
  x = 'Estimates of the LMMC Model', y = 'Estimates from Substitution')

save(Plot_Low_Individual_Variance, file = "../Rdata_Files/Plot_Low_Individual_Variance.Rda")




tobit_betas_individual_medium <- betas %>% 
  filter(Method == "Tobit") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.5)


museum_betas_individual_medium <- betas %>% 
  filter(Method == "Museum") %>% 
  select(-(Method)) %>% 
  filter(Std == 0.5)

betas_spread_individual_medium <- tobit_betas_individual_medium %>% 
  mutate(Museum_Beta = museum_betas_individual_medium$Beta)


Plot_Medium_Individual_Variance <- betas_spread_individual_medium %>% 
  ggplot(aes(x=Beta, y=Museum_Beta, col = `Random Effects`, shape = `Random Effects`)) +
  facet_grid(Slope_Perc ~ `Limit fraction`) +
  geom_point(alpha = 0.35) + 
  theme_minimal() +
  theme(plot.caption=element_text(hjust = 0), legend.background = element_rect(color = "black", 
    fill = NA, size =0.5, linetype = "solid"),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5),legend.title = element_text(color = "black", size = 8), legend.position = "top")+ 
   geom_hline(data = data.frame(Slope_Perc="1% yearly increase", y=log(1.01)), mapping=aes(yintercept=y)) +
   geom_vline(data = data.frame(Slope_Perc="1% yearly increase", x=log(1.01)), mapping=aes(xintercept=x)) +
  geom_hline(data = data.frame(Slope_Perc="5% yearly increase", y=log(1.05)), mapping=aes(yintercept=y))+
   geom_vline(data = data.frame(Slope_Perc="5% yearly increase", x=log(1.05)), mapping=aes(xintercept=x)) +
  labs(caption = "Figure 4: Plotting the estimated slopes for the Museum model and Tobit model against eachother having the variance of individual specimens
set to medium. The vertical and horizontal lines correspond to the true value of the slope.",
  x = 'Estimates of the LMMC Model', y = 'Estimates from Substitution')

  ggsave(plot = Plot_Medium_Individual_Variance, file = "Beta_Medium_Variance.pdf", scale = 1.5, width = 6)
  ggsave(plot = Plot_Low_Individual_Variance, file = "Beta_Low_Variance.pdf", scale = 1.5, width = 6)
  ggsave(plot = Plot_High_Individual_Variance, file = "Beta_High_Variance.pdf", scale = 1.5, width = 6)

save(Plot_Medium_Individual_Variance, file = "../Rdata_Files/Plot_Medium_Individual_Variance.Rda")
```