---
title: "Tables_md"
author: "Anton Holm"
date: '2020-04-16'
output:
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(kableExtra)

```

```{r, echo = FALSE}
load("../Rdata_Files/All_Summary_Stats.Rda")
load("../Rdata_Files/All_Summary_Stats_2.Rda")

#LOQ 30, Slope 1% Table
Full_Summary_Stats <- All_Summary_Stats %>% full_join(All_Summary_Stats_2)%>% mutate(`Random Effects` = replace(`Random Effects`, `Random Effects` == "HIGH", "High"))
save(Full_Summary_Stats, file = "../Rdata_Files/Full_Summary_Stats")


Summary_LOQ30_Slope1.01 <- Full_Summary_Stats %>% 
  filter(`Limit fraction` == 0.3) %>% 
  filter(Slope < 0.01) %>% 
  mutate(Slope = '1%') %>%
  mutate(bias = round(1000*bias, digits = 4)) %>% 
  mutate(Variance = round(1000*Variance, digits = 4)) %>% 
  mutate(MSE = round(1000*MSE, digits = 4)) %>% 
  select(-c(`Limit fraction`, Slope)) %>% 
  arrange(Std) %>% 
    mutate("Standard Error" = round(1000*sqrt(Variance/(100000))*2*abs(bias/1000), digits = 4)) %>% 
  mutate(Method = ifelse(Method == "Tobit", "LMMC", "Substitution")) %>% 
  mutate(MCvar = round(1000*(((sqrt(Variance/1000))/sqrt(198))*2*(sqrt(Variance/1000))), digits = 4))

colnames(Summary_LOQ30_Slope1.01) <- c("Individual Sd", "Random Effect", "Method", "$(E[\\hat{\\beta} - \\beta])^2$", "Coverage", "Var($\\hat{\\beta}$)", "MSE", "Se($(E[\\hat{\\beta} - \\beta])^2$)", "Se($Var(\\hat{\\beta})$)")

Table_LOQ30_Slope1.01 <- kable(Summary_LOQ30_Slope1.01, escape = FALSE, format = "latex", booktabs = T, align = "l", caption = "Summary statistics of simulations at 30\\% censored data and a 1\\% yearly increase. Statistics except coverage is multiplied by 1000.") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle") %>% 
  kable_styling(latex_options="scale_down")

save(Table_LOQ30_Slope1.01, file = "Table_LOQ30_Slope1.01.Rda")

Table_LOQ30_Slope1.01

#----------------------------------------------------------------------

#LOQ 30, Slope 5% Table
Summary_LOQ30_Slope1.05 <- Full_Summary_Stats %>% 
  filter(`Limit fraction` == 0.3) %>% 
  filter(Slope > 0.01) %>% 
  mutate(Slope = '5%') %>%
  mutate(bias = round(1000*bias, digits = 4)) %>% 
  mutate(Variance = round(1000*Variance, digits = 4)) %>% 
  mutate(MSE = round(1000*MSE, digits = 4)) %>% 
  select(-c(`Limit fraction`, Slope)) %>% 
  arrange(Std) %>% 
    mutate("Standard Error" = round(1000*sqrt(Variance/(100000))*2*abs(bias/1000), digits = 4))%>% 
  mutate(Method = ifelse(Method == "Tobit", "LMMC", "Substitution"))%>% 
  mutate(MCvar = round(1000*(((sqrt(Variance/1000))/sqrt(198))*2*(sqrt(Variance/1000))), digits = 4))

colnames(Summary_LOQ30_Slope1.05) <- c("Individual Sd", "Random Effect", "Method", "$(E[\\hat{\\beta} - \\beta])^2$", "Coverage", "Var($\\hat{\\beta}$)", "MSE", "Se($(E[\\hat{\\beta} - \\beta])^2$)", "Se($Var(\\hat{\\beta})$)")


Table_LOQ30_Slope1.05 <- kable(Summary_LOQ30_Slope1.05, escape = FALSE, format = "latex", booktabs = T, align = "l", caption = "Summary statistics of simulations at 30\\% censored data and a 5\\% yearly increase. Statistics except coverage is multiplied by 1000.") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle") %>% 
  kable_styling(latex_options="scale_down")
              

save(Table_LOQ30_Slope1.05, file = "Table_LOQ30_Slope1.05.Rda")

Table_LOQ30_Slope1.05


#----------------------------------------------------------------------

#LOQ 60, Slope 1% Table
Summary_LOQ60_Slope1.01 <- Full_Summary_Stats %>% 
  filter(`Limit fraction` == 0.6) %>% 
  filter(Slope < 0.01) %>% 
  mutate(Slope = '1%') %>%
  mutate(bias = round(1000*bias, digits = 4)) %>% 
  mutate(Variance = round(1000*Variance, digits = 4)) %>% 
  mutate(MSE = round(1000*MSE, digits = 4)) %>% 
  select(-c(`Limit fraction`, Slope)) %>% 
  arrange(Std) %>% 
    mutate("Standard Error" = round(1000*sqrt(Variance/(100000))*2*abs(bias/1000), digits = 4))%>% 
  mutate(Method = ifelse(Method == "Tobit", "LMMC", "Substitution"))%>% 
  mutate(MCvar = round(1000*(((sqrt(Variance/1000))/sqrt(198))*2*(sqrt(Variance/1000))), digits = 4))

colnames(Summary_LOQ60_Slope1.01) <- c("Individual Sd", "Random Effect", "Method", "$(E[\\hat{\\beta} - \\beta])^2$", "Coverage", "Var($\\hat{\\beta}$)", "MSE", "Se($(E[\\hat{\\beta} - \\beta])^2$)", "Se($Var(\\hat{\\beta})$)")



Table_LOQ60_Slope1.01 <- kable(Summary_LOQ60_Slope1.01,escape = FALSE, format = "latex", booktabs = T, align = "l", caption = "Summary statistics of simulations at 60\\% censored data and a 1\\% yearly increase. Statistics except coverage is multiplied by 1000.") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle") %>% 
  kable_styling(latex_options="scale_down")
              

save(Table_LOQ60_Slope1.01, file = "Table_LOQ60_Slope1.01.Rda")

Table_LOQ60_Slope1.01


#----------------------------------------------------------------------

#LOQ 60, Slope 5% Table
Summary_LOQ60_Slope1.05 <- Full_Summary_Stats %>% 
  filter(`Limit fraction` == 0.6) %>% 
  filter(Slope > 0.01) %>% 
  mutate(Slope = '5%') %>%
  mutate(bias = round(1000*bias, digits = 4)) %>% 
  mutate(Variance = round(1000*Variance, digits = 4)) %>% 
  mutate(MSE = round(1000*MSE, digits = 4)) %>% 
  select(-c(`Limit fraction`, Slope)) %>% 
  arrange(Std) %>% 
    mutate("Standard Error" = round(1000*sqrt(Variance/(100000))*2*abs(bias/1000), digits = 4))%>% 
  mutate(Method = ifelse(Method == "Tobit", "LMMC", "Substitution"))%>% 
  mutate(MCvar = round(1000*(((sqrt(Variance/1000))/sqrt(198))*2*(sqrt(Variance/1000))), digits = 4))

colnames(Summary_LOQ60_Slope1.05) <- c("Individual Sd", "Random Effect", "Method", "$(E[\\hat{\\beta} - \\beta])^2$", "Coverage", "Var($\\hat{\\beta}$)", "MSE", "Se($(E[\\hat{\\beta} - \\beta])^2$)", "Se($Var(\\hat{\\beta})$)")


Table_LOQ60_Slope1.05 <- kable(Summary_LOQ60_Slope1.05,escape = FALSE, format = "latex", booktabs = T, align = "l", caption = "Summary statistics of simulations at 60\\% censored data and a 5\\% yearly increase. Statistics except coverage is multiplied by 1000.") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle") %>% 
  kable_styling(latex_options="scale_down")
              

save(Table_LOQ60_Slope1.05, file = "Table_LOQ60_Slope1.05.Rda")

Table_LOQ60_Slope1.05
```